spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nityaranjan2004/microservice-cofiguration
          clone-on-start: true

server:
  port: 8085

okta:
  oauth2:
    issuer-uri: https://integrator-6727445.okta.com/oauth2/default
    audience: api://default