spring:
  application:
    name: RatingService

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Nitya@2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: always

  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-6727445.okta.com/oauth2/default
server:
  port: 8083

okta:
  oauth2:
    issuer-uri: https://integrator-6727445.okta.com/oauth2/default
    audience: api://default
